# Generated by Django 5.1.1 on 2024-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailsettings",
            old_name="client",
            new_name="clients",
        ),
        migrations.AddField(
            model_name="mailsettings",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активация рассылки"),
        ),
    ]
