# Generated by Django 4.2 on 2024-10-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sendler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="mailsettings",
            name="clients",
            field=models.ManyToManyField(
                help_text="выберете клиентов для рассылки",
                related_name="mailings",
                to="sendler.client",
                verbose_name="клиенты",
            ),
        ),
        migrations.AddField(
            model_name="mailsettings",
            name="message",
            field=models.ForeignKey(
                help_text="выберете сообщение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="sendler.message",
                verbose_name="сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailsettings",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="log",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="sendler.mailsettings",
                verbose_name="рассылка",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
