# Generated by Django 4.2 on 2024-10-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sendler", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailsettings",
            options={
                "permissions": [
                    ("can_view_mail_settings", "Может просматривать рассылки"),
                    ("can_edit_mail_settings", "Может отключать рассылки"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
